In [1]:
import numpy as np


---
# Matrix Zoo
---


In [13]:
# square matrices

S = np.random.randn(5,5)
R = np.random.randn(5,2)
print(S), print(' ')
print(R)
print()
# identity

I = np.eye(3)
print(I) 
print()

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D), print(' ')

# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(L)
print()
print(U)

# concatenate matrices (sizes must match!)
A = np.random.randn(4,2)
B = np.random.randn(4,4)
C = np.concatenate((A,B),axis=1)
print(C)

[[ 0.02937617  1.30466143  0.40004161 -0.35478564 -0.22581604]
 [ 1.40088754 -0.54769433  0.34719376  0.60494991  0.74293363]
 [ 0.56273107 -0.5151296   2.21730804 -1.3531857   0.2008954 ]
 [-1.80684182 -0.56770346  0.11047131  0.14643193  0.77368207]
 [ 1.3608623  -1.05024487 -0.48448011  0.40640255  1.20573397]]
 
[[ 0.48075792  0.12789743]
 [ 0.19065128 -1.37777783]
 [-0.34935895 -0.05632724]
 [-0.97806965  1.69946519]
 [-0.33284297  2.13806038]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
 
[[ 0.47012805  0.          0.          0.          0.        ]
 [-0.15051127 -0.61055689  0.          0.          0.        ]
 [ 1.96083867 -0.34446517 -0.31954583  0.          0.        ]
 [ 1.11771068 -0.27179978  0.75646878  0.94794217  0.        ]
 [ 0.07239056  0.075159   -0.53829128 -2.305914   -0.74036746]]

[[ 0.47012805 -0.54636284  0.23693388 -0.06011806 -1.01912467]
 [ 0.         -0.61055689  1.16054875 -1.8420792  -0.471999


---
# Matrix addition and subtraction
---


In [19]:
# create random matrix

A = np.random.randn(5,4)
B = np.random.randn(5,4)
C = np.random.randn(5,4)

# try to add them
A+B
B+C

# "shifting" a matrix
l = .3 #lambda
N = 5 # size of matrix
D = np.random.randn(N,N) # can shift only square matrix

Ds = D + l*np.eye(N)

print(D)
print()
print(Ds)
# Ds has changed only diagonal elements


[[-0.01168246 -0.97191098  0.09104208 -1.90739991  0.21830995]
 [ 1.51701538 -0.15044115  0.44044386 -1.16834966  0.10721591]
 [-0.57685662 -0.20429869 -1.09500076  1.70303175 -0.70899522]
 [-0.03740859 -1.52788582 -0.25671475  1.33506007 -0.69480048]
 [-1.0056585   1.01749745 -0.20625396  0.4233557  -1.60276144]]

[[ 0.28831754 -0.97191098  0.09104208 -1.90739991  0.21830995]
 [ 1.51701538  0.14955885  0.44044386 -1.16834966  0.10721591]
 [-0.57685662 -0.20429869 -0.79500076  1.70303175 -0.70899522]
 [-0.03740859 -1.52788582 -0.25671475  1.63506007 -0.69480048]
 [-1.0056585   1.01749745 -0.20625396  0.4233557  -1.30276144]]



---
# Scalar Multiplication
---


In [21]:
# define ,atrix and scalar

M = np.array([[1,2],[2,5]])
s = 2

print(M*s)
print()
print(s*M)

[[ 2  4]
 [ 4 10]]

[[ 2  4]
 [ 4 10]]


In [25]:
# whether two random matrices s(A+B) = sA +sB
m=7
n=5

A = np.random.randn(m,n)
B = np.random.randn(m,n)
# scalar
l = np.random.randn()

resA = s*(A+B)
resB = s*A + s*B

print(resA)
print()
print(resB)
print()
print(resA-resB)

# yes. it is same

[[-2.22025738  1.54827903  1.58352818  0.94853205 -2.14122458]
 [-0.64427297 -1.31869392  1.59389129 -5.4663184   0.40167754]
 [ 1.87762418  3.30966269 -1.32887191 -2.48700589  1.78826167]
 [ 3.16367877 -0.51945379  4.86471059 -4.15259241  0.04498734]
 [ 0.29029029  0.20008991  2.98225479  0.91859357  1.06093782]
 [ 3.42412652 -0.39901514 -0.1890929   1.45656424  3.22186591]
 [ 2.70281061 -1.79127068 -5.03921698 -1.80356298  3.42936313]]

[[-2.22025738  1.54827903  1.58352818  0.94853205 -2.14122458]
 [-0.64427297 -1.31869392  1.59389129 -5.4663184   0.40167754]
 [ 1.87762418  3.30966269 -1.32887191 -2.48700589  1.78826167]
 [ 3.16367877 -0.51945379  4.86471059 -4.15259241  0.04498734]
 [ 0.29029029  0.20008991  2.98225479  0.91859357  1.06093782]
 [ 3.42412652 -0.39901514 -0.1890929   1.45656424  3.22186591]
 [ 2.70281061 -1.79127068 -5.03921698 -1.80356298  3.42936313]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0


---
# Transpose
---


In [26]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T), print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]


In [27]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(np.matrix(C).H) # note the sign flips!


[[4.+1.j 3.+0.j 2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]



---
# Diagonal and Trace
---


In [34]:
M = np.round(5*np.random.randn(4,4))

# Extract the diagonal
d = np.diag(M)

# notice the two ways of using the diag function

d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print()
print(D)


# trace as sum of diagonal elemenbts

tr = np.trace(M)
tr2 = sum(np.diag(M))

print(tr,tr2)


[ 0.  2.  1. -2.]

[[ 0.  0.  0.  0.]
 [ 0.  2.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -2.]]
1.0 1.0


In [40]:
# The linearity of traces
# determine the releationship between tr(A) + tr(B) = tr(A+B)
# determine the relastionship between the tr(l*A) And l*tr(A)

A = np.round(5*np.random.randn(4,4))
B = np.round(5*np.random.randn(4,4))
l = np.random.randn()

trA = np.trace(A)
trB = np.trace(B)

res1 = trA+trB
res2 = np.trace(A+B)

print(res1,res2)
#the releationship between tr(A) + tr(B) = tr(A+B)

resA = np.trace(l*A)
resB = l*np.trace(A)
print()
print(resA,resB)


1.0 1.0

-3.8762381995209125 -3.8762381995209125



---
# Broadcasting matrix arithmetic
---


In [48]:
# create a matrix
A = np.reshape(np.arange(1,13),(3,4),'F') # F=column, C=row

# and two vectors
r = [ 10, 20, 30, 40 ]
c = [ 100, 200, 300 ]

print(A), print(' ')
print(r), print(' ')
print(c), print(' ');


[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
 
[10, 20, 30, 40]
 
[100, 200, 300]
 


In [53]:
# broadcast on the rows
print(A+r), print(' ')

# broadcast on the columns
#print(A+c)
print(A+np.reshape(c,(len(c),1))) # only works for explicit column vectors

[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]
 
[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]
