In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math


---
# Computing rank: theory and practice
---


In [ ]:
# make a matrix

m=4
n=6

# create a matrix
A = np.random.randn(m,n)

# what is the largest possible rank?
ra = np.linalg.matrix_rank(A)
print(f'Rank: {ra}')

# set last colums to be repeated of penultimate

B = A
B[:,-1] = B[:,-2]
ra_1 = np.linalg.matrix_rank(B)
print(f'Rank: {ra_1}')

# set last row to be repeated of penultimate

C = A
C[-1,:] = C[-2,:]
ra_2 = np.linalg.matrix_rank(C)
print(f'Rank: {ra_2}')

In [ ]:
## adding noise to a rank-deficient matrix

# square for convenience
A = np.round( 10*np.random.randn(m,m) )

# reduce the rank
A[:,-1] = A[:,-2]

# noise level
noiseamp = .000001 # Shifting

# add the noise
B = A + noiseamp*np.random.randn(m,m)

print('rank (w/o noise) = ' + str(np.linalg.matrix_rank(A)))
print('rank (with noise) = ' + str(np.linalg.matrix_rank(B)))



---
# Reduced-rank matrix using multiplication
---


In [ ]:
# create a 10x10 matrix with rank =4

A = np.random.randn(10,4)
B = np.random.randn(4,10)
C = A@B
np.linalg.matrix_rank(C)

# generalize the procedure to create any mxn matrix with rank r

m = 8
n = 47
r = 4

A1 = np.random.randn(m,r) @ np.random.randn(r,n)
print(np.shape(A1))
print(np.linalg.matrix_rank(A1))


---
# Scalar multiplication and rank
---

In [30]:
# Determine whether matrix rank is invariant to scalar multiplication
# rank(A) = or!= lambda*A

# create two matrices. full rank and two matrices reduced rank
#A = np.random.randn(5,5)
#B = np.random.randn(5,5)
#B[-1,:] = B[-2,:]

m = 6
n = 4
A = np.random.randn(m,n) * np.random.randn(n)
B = np.random.randn(m,n-1) * np.random.randn(n-1)

# creatre scalar
lam = 121212 #(But if 0, then we can change rank of matrix)

# print rank of the matrix (A.B.C.D)

ran1 = np.linalg.matrix_rank(A)
ran2 = np.linalg.matrix_rank(B)

print(f'Rank Of A:{ran1}')
print(f'Rank Of B:{ran2}')

# Check l*F or l*rank(F)

ran3 = np.linalg.matrix_rank(lam*A)
ran4 = np.linalg.matrix_rank(lam*B)

print(f'Rank Of lam x A:{ran3}')
print(f'Rank Of lam x B:{ran4}')

Rank Of A:4
Rank Of B:3
Rank Of lam x A:4
Rank Of lam x B:3



---
# Rank of a product btw two Matrices
---

In [35]:
m = 16
n = 3

A = 10*np.random.randn(m,n)

AtA = A@A.T
AAt = A.T@A

print(f'Rank AtA: {np.linalg.matrix_rank(AtA)}')
print(f'Rank AAt: {np.linalg.matrix_rank(AAt)}')

Rank AtA: 3
Rank AAt: 3



---
# Rank of multiplied and sum Matrices
---

In [40]:
# Generate two M

m =2
n =5
A = np.random.randn(m,n)
B = np.random.randn(m,n)

print(f'Rank A: {np.linalg.matrix_rank(A)}')
print(f'Rank B: {np.linalg.matrix_rank(B)}')
print()

# compute ATA and BTB
ATA = A.T@A
BTB = B.T@B
print(f'Rank AT: {np.linalg.matrix_rank(ATA)}')
print(f'Rank BT: {np.linalg.matrix_rank(BTB)}')

# Find ranks, ranks ATA, BTA

C = ATA + BTB
print(f'Rank C: {np.linalg.matrix_rank(C)}')

# Conclusion: We got a new Matrix with new info. With two addition geometric dimension that were not present in a origin matrices


Rank A: 2
Rank B: 2

Rank AT: 2
Rank BT: 2
Rank C: 4



---
# Making a matrix a full-rank by shifting
---

In [41]:
# size of matrix
m = 30

# create the square symmetric matrix
A = np.random.randn(m,m)
A = np.round( 10*A.T@A )

# reduce the rank
A[:,0] = A[:,1]

# shift amount (l=lambda)
l = .01

# new matrix
B = A + l*np.eye(m,m)

# print information
print('rank(w/o shift) = %d' %np.linalg.matrix_rank(A))
print('rank(with shift) = %d' %np.linalg.matrix_rank(B))

rank(w/o shift) = 29
rank(with shift) = 30


In [46]:
A = np.random.randn(10,4)
B = np.random.randn(4,10)
C = A@B
np.linalg.matrix_rank(C)

# generalize the procedure to create any mxn matrix with rank r

m = 8
n = 8
r = 4
lambd = .01

A1 = np.random.randn(m,r) @ np.random.randn(r,n)
B = A1+l*np.eye(m,n)
print(np.shape(A1))
print(np.linalg.matrix_rank(A1))
print(np.linalg.matrix_rank(B))

# So shifting allows us to get full rank matrix

(8, 8)
4
8


---
# Is this vector in the span of this set?
---

To determine whether some vector is contained in the span of some set of vectors.

In [60]:
# determine whether this vector 
v = np.array([[1,2,3,4]]).T
print(v)
print()

# in the span of these vectors

S = np.vstack(([4,3,6,2],[0,4,0,1])).T
T = np.vstack(([1,2,2,2],[0,0,1,2])).T
print(S)
print()
print(T)

Sv = np.concatenate((S,v),axis=1)
Tv = np.concatenate((T,v),axis = 1)
print(Sv)

print()

print(np.linalg.matrix_rank(Sv))
print(np.linalg.matrix_rank(Tv))

# So, as original Matrix S had rank = 2 and after adding vector v, the total rank increased to 3, 
# means that vector v is not in span of S

# while v is in span of T

[[1]
 [2]
 [3]
 [4]]

[[4 0]
 [3 4]
 [6 0]
 [2 1]]

[[1 0]
 [2 0]
 [2 1]
 [2 2]]
[[4 0 1]
 [3 4 2]
 [6 0 3]
 [2 1 4]]

3
2
